//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Contract.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP.Contract.Application.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор отсутствует в системе.
        /// </summary>
        internal static string ContractNotExist {
            get {
                return ResourceManager.GetString("ContractNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление договора с привязкой к закупке невозможно.
        /// </summary>
        internal static string ContractTiesToPurchase {
            get {
                return ResourceManager.GetString("ContractTiesToPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось привязать закупку к договору.
        /// </summary>
        internal static string FailedToBindPurchaseToContract {
            get {
                return ResourceManager.GetString("FailedToBindPurchaseToContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудалось загрузить файл.
        /// </summary>
        internal static string LoadError_FaultLoad {
            get {
                return ResourceManager.GetString("LoadError_FaultLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractDocuments.
        /// </summary>
        internal static string NameBucket_ContractDocuments {
            get {
                return ResourceManager.GetString("NameBucket_ContractDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закупка не может быть привязана к договору, так как не соответствует условиям.
        /// </summary>
        internal static string PurchaseCannotBeTied {
            get {
                return ResourceManager.GetString("PurchaseCannotBeTied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закупка отсутствует в системе.
        /// </summary>
        internal static string PurchaseNotExist {
            get {
                return ResourceManager.GetString("PurchaseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания действия договора не может быть меньше даты начала действия договора.
        /// </summary>
        internal static string ValidationError_ContractFinishDate {
            get {
                return ResourceManager.GetString("ValidationError_ContractFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала действия договора не может быть больше даты окончания действия договора.
        /// </summary>
        internal static string ValidationError_ContractStartDate {
            get {
                return ResourceManager.GetString("ValidationError_ContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атрибуты: Номер, Статус, Заказчик, Поставщик доступны для редактирования только в статусе Черновик.
        /// </summary>
        internal static string ValidationError_DraftDenyFieldsEdit {
            get {
                return ResourceManager.GetString("ValidationError_DraftDenyFieldsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не корректно заполнено.
        /// </summary>
        internal static string ValidationError_NotBeNull {
            get {
                return ResourceManager.GetString("ValidationError_NotBeNull", resourceCulture);
            }
        }
    }
}
